project:
  type: website

website:
  title: "LaCuesta HOA"
  page-footer:
    left: "built with ❤️  and [Quarto](https://quarto.org/)"
    right: "on the right"
  search: false
  navbar:
    right:
      - href: index.qmd
        text: home
      - href: about.qmd
        text: about
      - href: resources.qmd
        text: resources
      - href: board.qmd
        text: board
      - href: faq.qmd
        text: FAQ

format:
  html:
    theme: [sandstone, style/lacuestaweb.scss]
    css: styles.css
    toc: false
    link-external-icon: true
    link-external-newwindow: true
